language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "pip install coveralls"
script:
  - "python manage.py test"
branches:
    only:
      - master
      - will/upgrade-django-rest-framework
after_success:
  coveralls
