language: python
matrix:
  include:
    - python: '2.7'
      env: 'TOXENV=django111'
    - python: '3.5'
      env: 'TOXENV=django111'
    - python: '3.6'
      env: 'TOXENV=django20'
    - python: '3.6'
      env: 'TOXENV=django21'
    - python: '3.7'
      env: 'TOXENV=django20'
    - python: '3.7'
      env: 'TOXENV=django21'
  allow_failures:
    - python: '3.7'
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success: coveralls
# Set password via "travis encrypt --add deploy.password"; for details, see
# https://docs.travis-ci.com/user/deployment/pypi
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
  password:
    secure: JGKw0H2Hl1i3OuJ+54hGX/YImhWe+MvkkeFZDynpBKir8XD+E/fbz2lvvmggIrMsawkE5qlOjK8f4d4LMzwL51Ln0EmuIkhUceXLDihrEymZu97uAWbT5qR55RrfwZk/qaYV8JHAszBD3yLA5VOyDLTiDt9s2ilZDQqQqecX514=
